apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cliente
  labels:
    name: ms-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cliente
  template:
    metadata:
      labels:
        app: ms-cliente
    spec:
      containers:
      - name: ms-cliente
        image: pabloldias/soat1-grupo18-ms-cliente:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://fiap-ms-cliente.cr0dnn5xiohv.us-east-1.rds.amazonaws.com:5432/fiap_ms_cliente
        - name: SPRING_DATASOURCE_USERNAME
          value: dbuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: dbpassword
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        ports:
        - containerPort: 8080
