name: Build and test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  microservices-deploy:
    uses: soat1-grupo18/fase3-reusable-github-workflows/.github/workflows/microservices-deploy.yml@main
    with:
      microservice-id: soat1-grupo18-ms-cliente
    secrets: inherit

  curl-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run docker compose
        run: |
          set -e
          docker compose up -d

      - name: Wait the application becomes ready
        run: |
          set -e

          while ! curl --fail --url http://localhost:8080/actuator/health;
            do echo "Aguardando aplicação ficar online..."; sleep 5;
          done;

      - name: Test - Creates a customer
        id: test-creates-a-customer
        run: |
          set -e

          curl --fail \
            --request POST \
            --url http://localhost:8080/clientes \
            --header 'Content-Type: application/json' \
            --data '{ "nome": "John Carmack", "cpf": "11122233344", "telefone": "11911114444" }' | tee output.json

          echo "cliente-id=$(cat output.json | jq --raw-output '.id')" >> $GITHUB_OUTPUT
          echo "cliente-cpf=$(cat output.json | jq --raw-output '.telefone')" >> $GITHUB_OUTPUT

      - name: Test - Retrieves the customer
        id: test-retrieves-the-customer
        run: |
          set -e

          curl --fail \
            --request GET \
            --url "http://localhost:8080/clientes/${{ steps.test-creates-a-customer.outputs.cliente-cpf }}" | tee output.json

      - name: Stop docker compose
        run: |
          docker compose stop